remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
repo_url: "https://github.com/pam-d/about-phlpost"
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
